# Generated by Django 5.2.1 on 2025-05-22 10:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 5, 22, 15, 45, 27, 788749))),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.event')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('event', 'version_number')},
            },
        ),
    ]
